spring:
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    connect-timeout: 5000
    lettuce:
      shutdown-timeout: 100ms

server:
  port: 8080

logging:
  level:
    org.springframework.data.redis: DEBUG